In [1]:
#!pip install openpyxl
import pandas as pd
import numpy as np

# Set maximum rows to display (adjust the number as needed)
pd.set_option('display.max_rows', None)

# Set maximum columns to display (adjust the number as needed)
pd.set_option('display.max_columns', None)

In [2]:
# Read Excel data file
df = pd.read_excel("Faith Global Attendance Dataset.xlsx")
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,Campus,Male-Adult,Female-Adult,NaN,Kids /Teen,Total,Global total,Comments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-01 00:00:00,Lagos,1082,1630,NaN,160,2872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-01 00:00:00,Abuja,445,572,NaN,30,1047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-01 00:00:00,PHC,176,210,NaN,21,407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Select columns from index 10 (inclusive) to 25 (exclusive)
cols_to_drop = df.columns[9:26]  

# Drop the selected columns (handles potential mixed data types)
df.drop(cols_to_drop, axis=1, inplace=True)

# Print the modified DataFrame
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,Campus,Male-Adult,Female-Adult,NaN,Kids /Teen,Total,Global total,Comments
2,2024-01-01 00:00:00,Lagos,1082,1630,NaN,160,2872,NaN,NaN
3,2024-01-01 00:00:00,Abuja,445,572,NaN,30,1047,NaN,NaN
4,2024-01-01 00:00:00,PHC,176,210,NaN,21,407,NaN,NaN

In [4]:
# drop extra column not in range of 9:26, copy data 
drop_extra = df.drop(columns = ["Unnamed: 4"])
data = drop_extra.copy()
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,Comments
2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN
3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN
4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN

In [5]:
# Drop rows with NaN values in 'column_name' column
drop_nans = data[data["Unnamed: 0"].notna()]
drop_nans.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
1,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,Comments
2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN
3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN
4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN
5,2024-01-01 00:00:00,Ibadan,214,282,25,521,NaN,NaN

In [6]:
# Count the occurrences of "Date" (case-insensitive) in 'Unnamed: 0' column
column_values = []
counter = 0

for i in drop_nans["Unnamed: 0"]:
    if "Date" in str(i):  # Check if 'Date' is found (converted to string for case-insensitive matching)
        counter += 1
    column_values.append(counter)
    
# Print the list containing counts
column_values

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 23,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 34,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 35,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 36,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 37,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 39,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 41,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 42,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 43,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 44,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 45,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 46,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 47,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 50,
 50,
 50,
 ...]

In [7]:
# Add a new column named "Iteration" to 'drop_nans' DataFrame with values from 'column_values'
iter_cols = drop_nans.copy()  # Create a copy to avoid modifying original DataFrame

iter_cols["Iteration"]= column_values

# Print the DataFrame including the new column
iter_cols

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Iteration
1,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,Comments,1
2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN,1
3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN,1
4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN,1
5,2024-01-01 00:00:00,Ibadan,214,282,25,521,NaN,NaN,1
6,2024-01-01 00:00:00,Ife,85,134,0,219,NaN,NaN,1
7,2024-01-01 00:00:00,Canada,84,127,18,229,NaN,NaN,1
8,2024-01-01 00:00:00,UK (Birm),0,0,0,0,NaN,No physical service held.,1
9,2024-01-01 00:00:00,UK (London),0,0,0,0,5295,No physical service held.,1
10,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,2
11,2024-01-08 00:00:00,Lagos,1303,2028,161,3492,NaN,NaN,2
12,2024-01-08 00:00:00,Abuja,595,1140,48,1783,NaN,NaN,2
13,2024-01-08 00:00:00,PHC,186,268,20,474,NaN,NaN,2
14,2024-01-08 00:00:00,Ibadan,214,369,25,608,NaN,NaN,2
15,2024-01-08 00:00:00,Ife,97,130,3,230,NaN,NaN,2
16,2024-01-08 00:00:00,Canada,94,126,14,234,NaN,NaN,2
17,2024-01-08 00:00:00,UK (Birm),33,57,2,92,NaN,NaN,2
18,2024-01-08 00:00:00,UK (London),71,119,2,192,7105,NaN,2
19,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,3
20,2024-01-15 00:00:00,Lagos,1461,2046,162,3669,NaN,NaN,3
21,2024-01-15 00:00:00,Abuja,595,822,46,1463,NaN,NaN,3
22,2024-01-15 00:00:00,PHC,141,290,33,464,NaN,NaN,3
23,2024-01-15 00:00:00,Ibadan,326,534,35,895,NaN,NaN,3
24,2024-01-15 00:00:00,Ife,110,145,4,259,NaN,NaN,3
25,2024-01-15 00:00:00,Canada,92,125,14,231,NaN,NaN,3
26,2024-01-15 00:00:00,UK (Birm),47,64,3,114,NaN,NaN,3
27,2024-01-15 00:00:00,UK (London),66,127,6,199,NaN,NaN,3
28,2024-01-15 00:00:00,Dallas,18,27,0,45,NaN,NaN,3
29,2024-01-15 00:00:00,Uyo,135,156,9,300,7639,NaN,3
30,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,4
31,2024-01-22 00:00:00,Lagos,1594,2315,174,4083,NaN,NaN,4
32,2024-01-22 00:00:00,Abuja,518,788,53,1359,NaN,NaN,4
33,2024-01-22 00:00:00,PHC,193,291,24,508,NaN,NaN,4
34,2024-01-22 00:00:00,Ibadan,247,421,33,701,NaN,NaN,4
35,2024-01-22 00:00:00,Ife,113,157,4,274,NaN,NaN,4
36,2024-01-22 00:00:00,Canada,101,170,15,286,NaN,NaN,4
37,2024-01-22 00:00:00,UK (Birm),50,63,2,115,NaN,NaN,4
38,2024-01-22 00:00:00,UK (London),58,124,1,183,NaN,NaN,4
39,2024-01-22 00:00:00,Dallas,18,23,0,41,NaN,NaN,4
40,2024-01-22 00:00:00,Uyo,81,96,11,188,7738,NaN,4
41,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,5
42,2024-01-29 00:00:00,Lagos,1966,1597,182,3745,NaN,NaN,5
43,2024-01-29 00:00:00,Abuja,535,827,87,1449,NaN,NaN,5
44,2024-01-29 00:00:00,PHC,168,264,27,459,NaN,NaN,5
45,2024-01-29 00:00:00,Ibadan,231,396,30,657,NaN,NaN,5
46,2024-01-29 00:00:00,Ife,92,115,2,209,NaN,NaN,5
47,2024-01-29 00:00:00,Canada,110,138,18,266,NaN,NaN,5
48,2024-01-29 00:00:00,UK (Birm),51,639,2,692,NaN,NaN,5
49,2024-01-29 00:00:00,UK (London),62,143,5,210,NaN,NaN,5
50,2024-01-29 00:00:00,Dallas,20,22,1,43,NaN,NaN,5
51,2024-01-29 00:00:00,Uyo,86,79,6,171,7901,NaN,5
52,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,6
53,2024-02-05 00:00:00,Lagos,1461,2073,167,3701,NaN,NaN,6
54,2024-02-05 00:00:00,Abuja,528,806,64,1398,NaN,NaN,6
55,2024-02-05 00:00:00,PHC,180,279,22,481,NaN,NaN,6
56,2024-02-05 00:00:00,Ibadan,246,401,30,677,NaN,NaN,6
57,2024-02-05 00:00:00,Ife,110,150,4,264,NaN,NaN,6
58,2024-02-05 00:00:00,Canada,120,169,23,312,NaN,NaN,6
59,2024-02-05 00:00:00,UK (Birm),63,77,6,146,NaN,NaN,6
60,2024-02-05 00:00:00,UK (London),74,134,5,213,NaN,NaN,6
61,2024-02-05 00:00:00,Uyo,73,94,7,174,NaN,NaN,6
62,2024-02-05 00:00:00,Dallas,25,21,1,47,NaN,NaN,6
63,2024-02-05 00:00:00,Abeokuta,118,202,8,328,7741,NaN,6
64,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,7
65,2024-02-12 00:00:00,Lagos,2236,1476,171,3883,NaN,NaN,7
66,2024-02-12 00:00:00,Abuja,532,805,52,1389,NaN,NaN,7
67,2024-02-12 00:00:00,PHC,201,339,30,570,NaN,NaN,7
68,2024-02-12 00:00:00,Ibadan,278,486,38,802,NaN,NaN,7
69,2024-02-12 00:00:00,Ife,112,177,5,294,NaN,NaN,7
70,2024-02-12 00:00:00,Canada,118,188,20,326,NaN,NaN,7
71,2024-02-12 00:00:00,Uyo,80,106,2,188,NaN,NaN,7
72,2024-02-12 00:00:00,UK (Birm),54,89,2,145,NaN,NaN,7
73,2024-02-12 00:00:00,UK (London),73,145,3,221,NaN,NaN,7
74,2024-02-12 00:00:00,US - Dallas,21,23,0,44,NaN,NaN,7
75,2024-02-12 00:00:00,Abeokuta,69,128,7,204,8066,NaN,7
76,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,8
77,2024-02-19 00:00:00,Lagos,1960,3024,128,5112,NaN,NaN,8
78,2024-02-19 00:00:00,Lagos (YAF),445,896,10,1351,NaN,NaN,8
79,2024-02-19 00:00:00,Abuja,477,742,64,1283,NaN,NaN,8
80,2024-02-19 00:00:00,PHC,197,251,43,491,NaN,NaN,8
81,2024-02-19 00:00:00,Ibadan,160,227,24,738,NaN,NaN,8
82,2024-02-19 00:00:00,Ife,99,158,19,276,NaN,NaN,8
83,2024-02-19 00:00:00,Canada,121,220,19,360,NaN,NaN,8
84,2024-02-19 00:00:00,UK (Birm),60,85,6,151,NaN,NaN,8
85,2024-02-19 00:00:00,UK (London),85,142,3,230,NaN,NaN,8
86,2024-02-19 00:00:00,Uyo,54,78,2,134,NaN,NaN,8
87,2024-02-19 00:00:00,Dallas,20,19,0,39,9013,NaN,8
88,2024-02-19 00:00:00,Abeokuta,60,133,6,199,10364,NaN,8
89,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,9
90,2024-02-26 00:00:00,Lagos - Ikeja,473,579,58,1110,NaN,NaN,9
91,2024-02-26 00:00:00,Lagos - Yaba,119,161,4,284,NaN,NaN,9
92,2024-02-26 00:00:00,Lagos - VI,110,142,10,262,1656,NaN,9
93,2024-02-26 00:00:00,Lagos - Ago,NaN,NaN,NaN,no service,NaN,NaN,9
94,2024-02-26 00:00:00,Lagos - Ajah,NaN,NaN,NaN,no service,NaN,NaN,9
95,2024-02-26 00:00:00,Abuja - Utako,248,248,41,537,NaN,NaN,9
96,2024-02-26 00:00:00,Abuja - Mararaba,82,104,9,195,NaN,NaN,9
97,2024-02-26 00:00:00,Abuja - Lokogoma,121,166,11,298,1030,NaN,9
98,2024-02-26 00:00:00,PHC,124,206,19,349,NaN,NaN,9
99,2024-02-26 00:00:00,Ibadan,NaN,227,24,251,NaN,NaN,9
100,2024-02-26 00:00:00,Ife,NaN,NaN,NaN,no service,NaN,NaN,9
101,2024-02-26 00:00:00,Canada,107,167,21,295,NaN,NaN,9
102,2024-02-26 00:00:00,UK (Birm),79,132,5,216,NaN,NaN,9
103,2024-02-26 00:00:00,UK (London),231,112,7,350,NaN,NaN,9
104,2024-02-26 00:00:00,Uyo,NaN,NaN,NaN,no service,NaN,NaN,9
105,2024-02-26 00:00:00,Dallas,20,24,1,45,NaN,NaN,9
106,2024-02-26 00:00:00,Abeokuta,NaN,NaN,NaN,no service,4192,NaN,9
107,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,10
108,2024-03-05 00:00:00,Lagos - Ikeja,713,1137,131,1981,NaN,NaN,10
109,2024-03-05 00:00:00,Lagos - Yaba,214,339,11,564,NaN,NaN,10
110,2024-03-05 00:00:00,Lagos - VI,231,335,18,584,NaN,NaN,10
111,2024-03-05 00:00:00,Lagos - Ago,146,216,23,385,NaN,NaN,10
112,2024-03-05 00:00:00,Lagos - Ajah,103,104,15,222,NaN,NaN,10
113,2024-03-05 00:00:00,Abuja - Utako,264,369,35,668,NaN,NaN,10
114,2024-03-05 00:00:00,Abuja - Mararaba,98,124,8,230,NaN,NaN,10
115,2024-03-05 00:00:00,Abuja - Lokogoma,162,260,23,445,NaN,NaN,10
116,2024-03-05 00:00:00,PHC,173,299,36,508,NaN,NaN,10
117,2024-03-05 00:00:00,Ibadan,249,321,30,600,NaN,NaN,10
118,2024-03-05 00:00:00,Ife,101,88,5,194,NaN,NaN,10
119,2024-03-05 00:00:00,Canada,114,191,16,321,NaN,NaN,10
120,2024-03-05 00:00:00,UK (Birm),53,78,3,134,NaN,NaN,10
121,2024-03-05 00:00:00,UK (London),63,110,1,174,NaN,NaN,10
122,2024-03-05 00:00:00,Uyo,65,82,5,152,NaN,NaN,10
123,2024-03-05 00:00:00,Dallas,14,15,0,29,NaN,NaN,10
124,2024-03-05 00:00:00,Abeokuta,75,160,9,244,7435,NaN,10
125,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,11
126,2024-03-12 00:00:00,Lagos - Ikeja,729,1035,126,1890,NaN,NaN,11
127,2024-03-12 00:00:00,Lagos - Yaba,246,348,14,608,NaN,NaN,11
128,2024-03-12 00:00:00,Lagos - VI,243,357,21,621,NaN,NaN,11
129,2024-03-12 00:00:00,Lagos - Ago,159,250,42,451,NaN,NaN,11
130,2024-03-12 00:00:00,Lagos - Ajah,108,116,19,243,Lagos : 3813,NaN,11
131,2024-03-12 00:00:00,Abuja - Utako,304,443,40,787,NaN,NaN,11
132,2024-03-12 00:00:00,Abuja - Mararaba,95,125,13,233,NaN,NaN,11
133,2024-03-12 00:00:00,Abuja - Lokogoma,172,276,25,473,NaN,NaN,11
134,2024-03-12 00:00:00,PHC,203,275,39,517,NaN,NaN,11
135,2024-03-12 00:00:00,Ibadan,234,320,28,582,NaN,NaN,11
136,2024-03-12 00:00:00,Ife,105,125,3,233,NaN,NaN,11
137,2024-03-12 00:00:00,Canada,111,168,17,296,NaN,NaN,11
138,2024-03-12 00:00:00,UK (Birm),NaN,NaN,No service,No service,NaN,NaN,11
139,2024-03-12 00:00:00,UK (London),81,147,2,230,NaN,NaN,11
140,2024-03-12 00:00:00,Uyo,91,63,5,159,NaN,NaN,11
141,2024-03-12 00:00:00,Dallas,47,124,2,173,NaN,NaN,11
142,2024-03-12 00:00:00,Abeokuta,86,125,3,214,7710,NaN,11
143,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,12
144,2024-03-19 00:00:00,Lagos - Ikeja,651,925,98,1674,NaN,NaN,12
145,2024-03-19 00:00:00,Lagos - Yaba,192,272,11,475,NaN,NaN,12
146,2024-03-19 00:00:00,Lagos - VI,215,274,18,507,NaN,NaN,12
147,2024-03-19 00:00:00,Lagos - Ago,No service,NaN,NaN,0,2656,NaN,12
148,2024-03-19 00:00:00,Lagos - Ajah,79,100,11,190,NaN,NaN,12
149,2024-03-19 00:00:00,Abuja - Utako,267,433,43,743,NaN,NaN,12
150,2024-03-19 00:00:00,Abuja - Mararaba,107,114,11,232,1165,NaN,12
151,2024-03-19 00:00:00,Abuja - Lokogoma,170,253,24,447,NaN,NaN,12
152,2024-03-19 00:00:00,PHC,159,235,29,423,NaN,NaN,12
153,2024-03-19 00:00:00,Ibadan,228,294,23,545,NaN,NaN,12
154,2024-03-19 00:00:00,Ife,156,112,5,273,NaN,NaN,12
155,2024-03-19 00:00:00,Canada,121,163,21,305,NaN,NaN,12
156,2024-03-19 00:00:00,UK (Birm),40,62,2,104,NaN,NaN,12
157,2024-03-19 00:00:00,UK (London),84,91,2,177,NaN,NaN,12
158,2024-03-19 00:00:00,Uyo,NaN,NaN,NaN,0,NaN,NaN,12
159,2024-03-19 00:00:00,Dallas,14,20,0,34,NaN,NaN,12
160,2024-03-19 00:00:00,Abeokuta,93,138,3,234,6363,NaN,12
161,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,13
162,2024-03-26 00:00:00,Lagos - Ikeja,665,922,54,1641,NaN,NaN,13
163,2024-03-26 00:00:00,Lagos - Yaba,337,505,19,861,NaN,NaN,13
164,2024-03-26 00:00:00,Lagos - VI,286,219,17,522,NaN,NaN,13
165,2024-03-26 00:00:00,Lagos - Ago,88,128,28,244,NaN,NaN,13
166,2024-03-26 00:00:00,Lagos - Ajah,88,128,7,223,NaN,NaN,13
167,2024-03-26 00:00:00,Abuja - Utako,273,367,24,664,NaN,NaN,13
168,2024-03-26 00:00:00,Abuja - Mararaba,93,116,17,226,NaN,NaN,13
169,2024-03-26 00:00:00,Abuja - Lokogoma,187,272,22,481,NaN,NaN,13
170,2024-03-26 00:00:00,PHC,168,275,27,470,NaN,NaN,13
171,2024-03-26 00:00:00,Ibadan,253,383,34,670,NaN,NaN,13
172,2024-03-26 00:00:00,Ife,152,220,8,380,NaN,NaN,13
173,2024-03-26 00:00:00,Canada,201,360,31,592,NaN,Special Sunday Service,13
174,2024-03-26 00:00:00,UK (Birm),41,49,3,93,NaN,NaN,13
175,2024-03-26 00:00:00,UK (London),49,92,4,145,NaN,NaN,13
176,2024-03-26 00:00:00,UK (Manchester),61,98,10,169,NaN,NaN,13
177,2024-03-26 00:00:00,Uyo,70,85,2,157,NaN,NaN,13
178,2024-03-26 00:00:00,Dallas,16,24,0,40,NaN,NaN,13
179,2024-03-26 00:00:00,Abeokuta,113,132,5,250,7828,NaN,13
180,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,14
181,2024-04-02 00:00:00,Lagos - Ikeja,705,979,60,1744,NaN,NaN,14
182,2024-04-02 00:00:00,Lagos - Yaba,309,586,15,910,NaN,NaN,14
183,2024-04-02 00:00:00,Lagos - VI,360,325,16,701,NaN,NaN,14
184,2024-04-02 00:00:00,Lagos - Ago,133,221,35,389,NaN,NaN,14
185,2024-04-02 00:00:00,Lagos - Ajah,121,145,NaN,266,NaN,NaN,14
186,2024-04-02 00:00:00,Abuja - Utako,262,387,44,693,NaN,NaN,14
187,2024-04-02 00:00:00,Abuja - Mararaba,93,120,12,225,NaN,NaN,14
188,2024-04-02 00:00:00,Abuja - Lokogoma,192,293,28,513,NaN,NaN,14
189,2024-04-02 00:00:00,PHC,340,243,38,621,NaN,NaN,14
190,2024-04-02 00:00:00,Ibadan,303,518,44,865,NaN,NaN,14
191,2024-04-02 00:00:00,Ife,169,264,1,434,NaN,NaN,14
192,2024-04-02 00:00:00,Canada,125,172,24,321,NaN,NaN,14
193,2024-04-02 00:00:00,UK (Birm),44,87,2,133,NaN,NaN,14
194,2024-04-02 00:00:00,UK (London),70,129,3,202,NaN,NaN,14
195,2024-04-02 00:00:00,UK (Manchester),36,49,6,91,NaN,NaN,14
196,2024-04-02 00:00:00,Uyo,71,99,5,175,NaN,NaN,14
197,2024-04-02 00:00:00,Dallas,21,27,0,48,NaN,NaN,14
198,2024-04-02 00:00:00,Abeokuta,92,150,7,249,8580,NaN,14
199,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,15
200,2024-04-09 00:00:00,Lagos - Ikeja,683,856,28,1567,NaN,NaN,15
201,2024-04-09 00:00:00,Lagos - Yaba,303,515,8,826,NaN,NaN,15
202,2024-04-09 00:00:00,Lagos - VI,258,336,22,616,NaN,NaN,15
203,2024-04-09 00:00:00,Lagos - Ago,139,235,29,403,NaN,NaN,15
204,2024-04-09 00:00:00,Lagos - Ajah,110,134,13,257,NaN,NaN,15
205,2024-04-09 00:00:00,Abuja - Utako,274,384,49,707,NaN,NaN,15
206,2024-04-09 00:00:00,Abuja - Mararaba,93,120,12,225,NaN,NaN,15
207,2024-04-09 00:00:00,Abuja - Lokogoma,192,293,28,513,NaN,NaN,15
208,2024-04-09 00:00:00,PHC,222,338,41,601,NaN,NaN,15
209,2024-04-09 00:00:00,Ibadan,327,487,42,856,NaN,NaN,15
210,2024-04-09 00:00:00,Ife,140,211,6,357,NaN,NaN,15
211,2024-04-09 00:00:00,Canada,147,245,24,416,NaN,Special Sunday service,15
212,2024-04-09 00:00:00,UK (Birm),83,43,5,131,NaN,NaN,15
213,2024-04-09 00:00:00,UK (London),78,141,6,225,NaN,NaN,15
214,2024-04-09 00:00:00,UK (Manchester),39,48,6,93,NaN,NaN,15
215,2024-04-09 00:00:00,Uyo,71,101,4,176,NaN,NaN,15
216,2024-04-09 00:00:00,Dallas,27,32,1,60,NaN,NaN,15
217,2024-04-09 00:00:00,Abeokuta,75,104,2,181,8210,NaN,15
218,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,16
219,2024-04-16 00:00:00,Lagos - Ikeja,674,903,80,1657,NaN,NaN,16
220,2024-04-16 00:00:00,Lagos - Yaba,270,535,10,815,NaN,NaN,16
221,2024-04-16 00:00:00,Lagos - VI,223,279,20,522,NaN,NaN,16
222,2024-04-16 00:00:00,Lagos - Ago,146,240,32,418,NaN,NaN,16
223,2024-04-16 00:00:00,Lagos - Ajah,123,144,9,276,NaN,NaN,16
224,2024-04-16 00:00:00,Abuja - Utako,227,397,36,660,NaN,NaN,16
225,2024-04-16 00:00:00,Abuja - Mararaba,77,109,12,198,NaN,NaN,16
226,2024-04-16 00:00:00,Abuja - Lokogoma,173,256,24,453,NaN,NaN,16
227,2024-04-16 00:00:00,PHC,207,331,40,578,NaN,NaN,16
228,2024-04-16 00:00:00,Ibadan,299,482,51,832,NaN,NaN,16
229,2024-04-16 00:00:00,Ife,115,221,3,339,NaN,NaN,16
230,2024-04-16 00:00:00,Canada,127,183,24,334,NaN,NaN,16
231,2024-04-16 00:00:00,UK (Birm),42,66,6,114,NaN,NaN,16
232,2024-04-16 00:00:00,UK (London) S1,141,244,18,403,NaN,NaN,16
233,2024-04-16 00:00:00,UK (London) S2,109,206,12,327,NaN,NaN,16
234,2024-04-16 00:00:00,UK (Manchester),29,52,5,86,NaN,NaN,16
235,2024-04-16 00:00:00,Uyo,98,106,1,205,NaN,NaN,16
236,2024-04-16 00:00:00,Dallas,17,24,1,42,NaN,NaN,16
237,2024-04-16 00:00:00,Abeokuta,68,114,10,192,8451,NaN,16
238,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,17
239,2024-04-23 00:00:00,Lagos - Ikeja,594,848,69,1511,NaN,NaN,17
240,2024-04-23 00:00:00,Lagos - Yaba,280,489,19,788,NaN,NaN,17
241,2024-04-23 00:00:00,Lagos - VI,204,264,9,477,NaN,NaN,17
242,2024-04-23 00:00:00,Lagos - Ago,122,211,37,370,NaN,NaN,17
243,2024-04-23 00:00:00,Lagos - Ajah,98,115,11,224,NaN,NaN,17
244,2024-04-23 00:00:00,Abuja - Utako,276,360,33,669,NaN,NaN,17
245,2024-04-23 00:00:00,Abuja - Mararaba,78,121,14,213,NaN,NaN,17
246,2024-04-23 00:00:00,Abuja - Lokogoma,181,293,36,510,NaN,NaN,17
247,2024-04-23 00:00:00,PHC,222,286,30,538,NaN,NaN,17
248,2024-04-23 00:00:00,Ibadan,305,441,53,799,NaN,NaN,17
249,2024-04-23 00:00:00,Ife,116,196,3,315,NaN,NaN,17
250,2024-04-23 00:00:00,Canada,111,185,28,324,NaN,NaN,17
251,2024-04-23 00:00:00,UK (Birm),237,433,30,700,NaN,NaN,17
252,2024-04-23 00:00:00,UK (London),NaN,NaN,NaN,No service,No service,NaN,17
253,2024-04-23 00:00:00,UK (Manchester),NaN,NaN,NaN,No service,No service,NaN,17
254,2024-04-23 00:00:00,Uyo,89,118,5,212,NaN,NaN,17
255,2024-04-23 00:00:00,Dallas,21,30,NaN,51,NaN,NaN,17
256,2024-04-23 00:00:00,Abeokuta,62,122,5,189,7890,NaN,17
257,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,18
258,2024-04-30 00:00:00,Lagos - Ikeja,645,969,82,1696,NaN,NaN,18
259,2024-04-30 00:00:00,Lagos - Yaba,305,499,17,821,NaN,NaN,18
260,2024-04-30 00:00:00,Lagos - VI,221,269,20,510,NaN,NaN,18
261,2024-04-30 00:00:00,Lagos - Ago,143,248,26,417,NaN,NaN,18
262,2024-04-30 00:00:00,Lagos - Ajah,90,126,8,224,NaN,NaN,18
263,2024-04-30 00:00:00,Abuja - Utako,246,347,48,641,NaN,NaN,18
264,2024-04-30 00:00:00,Abuja - Mararaba,87,153,22,262,NaN,NaN,18
265,2024-04-30 00:00:00,Abuja - Lokogoma,170,290,30,490,NaN,NaN,18
266,2024-04-30 00:00:00,PHC,204,313,29,546,NaN,NaN,18
267,2024-04-30 00:00:00,Ibadan,317,460,31,808,NaN,NaN,18
268,2024-04-30 00:00:00,Ife,130,207,1,338,NaN,NaN,18
269,2024-04-30 00:00:00,Canada,118,187,18,323,NaN,NaN,18
270,2024-04-30 00:00:00,UK (Birm),46,73,8,127,NaN,NaN,18
271,2024-04-30 00:00:00,UK (London),74,120,3,197,NaN,NaN,18
272,2024-04-30 00:00:00,UK (Manchester),29,47,6,82,NaN,NaN,18
273,2024-04-30 00:00:00,Uyo,77,96,8,181,NaN,NaN,18
274,2024-04-30 00:00:00,Dallas,19,29,1,49,NaN,NaN,18
275,2024-04-30 00:00:00,Abeokuta,76,116,9,201,7913,NaN,18
276,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,19
277,2024-05-07 00:00:00,Lagos - Ikeja,727,978,119,1824,NaN,NaN,19
278,2024-05-07 00:00:00,Lagos - Yaba,411,724,25,1160,NaN,NaN,19
279,2024-05-07 00:00:00,Lagos - VI,227,331,21,579,NaN,NaN,19
280,2024-05-07 00:00:00,Lagos - Ago,166,267,36,469,NaN,NaN,19
281,2024-05-07 00:00:00,Lagos - Ajah,106,149,8,263,4295,NaN,19
282,2024-05-07 00:00:00,Abuja - Utako,270,350,28,648,NaN,NaN,19
283,2024-05-07 00:00:00,Abuja - Mararaba,81,130,15,226,NaN,NaN,19
284,2024-05-07 00:00:00,Abuja - Lokogoma,178,276,30,484,1358,NaN,19
285,2024-05-07 00:00:00,PHC,377,255,26,658,NaN,NaN,19
286,2024-05-07 00:00:00,Ibadan,344,458,50,852,NaN,NaN,19
287,2024-05-07 00:00:00,Ife,116,191,3,310,NaN,NaN,19
288,2024-05-07 00:00:00,Canada,134,186,21,341,NaN,NaN,19
289,2024-05-07 00:00:00,UK (Birm),50,73,7,130,NaN,NaN,19
290,2024-05-07 00:00:00,UK (London),61,146,5,212,NaN,NaN,19
291,2024-05-07 00:00:00,UK (Manchester),36,55,5,96,NaN,NaN,19
292,2024-05-07 00:00:00,Uyo,93,114,5,212,NaN,NaN,19
293,2024-05-07 00:00:00,Dallas,17,30,1,48,NaN,NaN,19
294,2024-05-07 00:00:00,Abeokuta,85,143,6,234,8746,NaN,19
295,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,20
296,2024-05-14 00:00:00,Lagos - Ikeja,924,843,95,1862,NaN,1767,20
297,2024-05-14 00:00:00,Lagos - Yaba,365,582,24,971,NaN,NaN,20
298,2024-05-14 00:00:00,Lagos - VI,223,324,35,582,NaN,NaN,20
299,2024-05-14 00:00:00,Lagos - Ago,231,150,32,413,NaN,NaN,20
300,2024-05-14 00:00:00,Lagos - Ajah,109,163,11,283,4111,NaN,20
301,2024-05-14 00:00:00,Abuja - Utako,294,389,31,714,NaN,NaN,20
302,2024-05-14 00:00:00,Abuja - Mararaba,95,114,22,231,NaN,NaN,20
303,2024-05-14 00:00:00,Abuja - Lokogoma,188,279,31,498,NaN,NaN,20
304,2024-05-14 00:00:00,PHC,240,308,31,579,NaN,NaN,20
305,2024-05-14 00:00:00,Ibadan,348,471,44,863,NaN,NaN,20
306,2024-05-14 00:00:00,Ife,129,217,3,349,NaN,NaN,20
307,2024-05-14 00:00:00,Canada,131,199,23,353,NaN,NaN,20
308,2024-05-14 00:00:00,UK (Birm),52,90,9,151,NaN,NaN,20
309,2024-05-14 00:00:00,UK (London),69,144,9,222,NaN,NaN,20
310,2024-05-14 00:00:00,UK(Manchester),39,59,5,103,NaN,NaN,20
311,2024-05-14 00:00:00,Uyo,82,94,6,182,NaN,NaN,20
312,2024-05-14 00:00:00,Dallas,22,28,2,52,NaN,NaN,20
313,2024-05-14 00:00:00,Abeokuta,63,164,10,237,8645,NaN,20
314,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,21
315,2024-05-21 00:00:00,Lagos - Ikeja,719,1055,77,1851,NaN,NaN,21
316,2024-05-21 00:00:00,Lagos - Yaba,368,588,19,975,NaN,NaN,21
317,2024-05-21 00:00:00,Lagos - VI,193,282,18,493,NaN,NaN,21
318,2024-05-21 00:00:00,Lagos - Ago,173,247,46,466,NaN,NaN,21
319,2024-05-21 00:00:00,Lagos - Ajah,132,126,19,277,NaN,NaN,21
320,2024-05-21 00:00:00,Abuja - Utako,295,415,45,755,NaN,NaN,21
321,2024-05-21 00:00:00,Abuja - Mararaba,106,142,11,259,NaN,NaN,21
322,2024-05-21 00:00:00,Abuja - Lokogoma,157,281,26,464,NaN,NaN,21
323,2024-05-21 00:00:00,PHC,226,343,32,601,NaN,NaN,21
324,2024-05-21 00:00:00,Ibadan,270,443,38,751,NaN,NaN,21
325,2024-05-21 00:00:00,Ife,121,221,3,345,NaN,NaN,21
326,2024-05-21 00:00:00,Canada,126,214,22,362,NaN,NaN,21
327,2024-05-21 00:00:00,UK (Birm),92,55,6,153,NaN,NaN,21
328,2024-05-21 00:00:00,UK (London),93,131,8,232,NaN,NaN,21
329,2024-05-21 00:00:00,UK (Manchester),33,58,6,97,482,NaN,21
330,2024-05-21 00:00:00,Uyo,87,129,9,225,NaN,NaN,21
331,2024-05-21 00:00:00,Dallas,22,23,0,45,NaN,NaN,21

In [8]:
#Filter for Rows with "Date" (Excluding NaN):
name_df = iter_cols[iter_cols["Unnamed: 0"].notna() & iter_cols["Unnamed: 0"].str.contains("Date")]

name_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Iteration
1,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,Comments,1
10,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,2
19,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,3
30,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,4
41,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,5

In [9]:
# Rename columns of 'name_df' DataFrame with more descriptive names
new_df = name_df.rename(columns = {"Unnamed: 0":"Date", "Unnamed: 1":"Campus", "Unnamed: 2":"Male-Adult",
                          "Unnamed: 3":"Female-Adult",	"Unnamed: 5":"Kids/Teen",	"Unnamed: 6":"Total",
                          "Unnamed: 7":"Global total",	"Unnamed: 8":"Comments"})
new_df.head()

,Date,Campus,Male-Adult,Female-Adult,Kids/Teen,Total,Global total,Comments,Iteration
1,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,Comments,1
10,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,2
19,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,3
30,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,4
41,Date,Campus,Male-Adult,Female-Adult,Kids /Teen,Total,Global total,NaN,5

In [10]:
# Filter rows where 'Unnamed: 0' does not have a value or does not contain 'Date' (case-insensitive)
noname_df = iter_cols[~(iter_cols["Unnamed: 0"].notna() & iter_cols["Unnamed: 0"].str.contains("Date"))]

# Show the first 5 rows of the new DataFrame
noname_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Iteration
2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN,1
3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN,1
4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN,1
5,2024-01-01 00:00:00,Ibadan,214,282,25,521,NaN,NaN,1
6,2024-01-01 00:00:00,Ife,85,134,0,219,NaN,NaN,1

In [11]:
# Rename columns with more descriptive names and 
clean_data = noname_df.rename(columns = {"Unnamed: 0":"Date", "Unnamed: 1":"Campus", "Unnamed: 2":"Male-Adult",
                          "Unnamed: 3":"Female-Adult",	"Unnamed: 5":"Kids/Teen",	"Unnamed: 6":"Total",
                          "Unnamed: 7":"Global total",	"Unnamed: 8":"Comments"})
#drop 'Iteration' column
clean_data = clean_data.drop(columns = ["Iteration"])

clean_data.head()

,Date,Campus,Male-Adult,Female-Adult,Kids/Teen,Total,Global total,Comments
2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN
3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN
4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN
5,2024-01-01 00:00:00,Ibadan,214,282,25,521,NaN,NaN
6,2024-01-01 00:00:00,Ife,85,134,0,219,NaN,NaN

In [12]:
# Reset index, keeping the old one as a column
clean_data = clean_data.reset_index(drop=False)

# Add a new column with unique IDs starting from 1
clean_data['unique_id'] = clean_data.index + 1 

clean_data.head()

,index,Date,Campus,Male-Adult,Female-Adult,Kids/Teen,Total,Global total,Comments,unique_id
0,2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN,1
1,3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN,2
2,4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN,3
3,5,2024-01-01 00:00:00,Ibadan,214,282,25,521,NaN,NaN,4
4,6,2024-01-01 00:00:00,Ife,85,134,0,219,NaN,NaN,5

In [13]:
clean_data.shape

(1053, 10)

In [14]:
new_clean_data = clean_data.copy()

#  Drops rows with NaN values or values equal to 0.
def cleaned_data(new_clean_data):
  # Drop rows with NaN in specified columns
  new_clean_data = new_clean_data.dropna(subset=['Male-Adult', 'Female-Adult', 'Kids/Teen'])

  # Keep rows where any of the specified columns are not 0
  new_clean_data = new_clean_data[new_clean_data[['Male-Adult', 'Female-Adult', 'Kids/Teen']].any(axis=1)]

  return new_clean_data

cleaned = cleaned_data(new_clean_data.copy())  # Apply logic to a copy

# Print the cleaned DataFrame
cleaned.head()

,index,Date,Campus,Male-Adult,Female-Adult,Kids/Teen,Total,Global total,Comments,unique_id
0,2,2024-01-01 00:00:00,Lagos,1082,1630,160,2872,NaN,NaN,1
1,3,2024-01-01 00:00:00,Abuja,445,572,30,1047,NaN,NaN,2
2,4,2024-01-01 00:00:00,PHC,176,210,21,407,NaN,NaN,3
3,5,2024-01-01 00:00:00,Ibadan,214,282,25,521,NaN,NaN,4
4,6,2024-01-01 00:00:00,Ife,85,134,0,219,NaN,NaN,5

In [15]:
cleaned = cleaned.drop(columns = ["index"])
cleaned.shape

(985, 9)

In [ ]:
"""
# to unpivot data
unpivoted_data = pd.melt(clean_data, id_vars=['index','unique_id', 'Date', 'Campus', 'Total','Global total', 'Comments'], 
                         var_name='Gender-Type', value_name='Attendees')
"""

In [20]:
# Save the DataFrame to CSV with the new index  
cleaned.to_csv("Faith Global Cleaned Data.csv", index=False) # Set index=False to exclude the original index
print("Saved Successfully")

Saved Successfully